name: "Deploy Recipes Book Frontend"
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Run command on remote server12
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USERNAME }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            cd ../recipe-book-front;
            git pull;
            export NVM_DIR=~/.nvm;
            source ~/.nvm/nvm.sh;
            npm install;
            npm run build;
            cd ../var/www;
            rm -r dist;
            cd ../../recipe-book-front;
            mv dist ../var/www;
